### ISSUE TITLE
UX: TODO

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#47]
- [x] Unify: Buttons
- [ ] Contacts: Activities
- [x] Calendar: Edit event - full page
- [x] Chat
  - [x] Message menu
  - [x] Emoji selector
- [x] Mail
  - [x] #75
  - [x] Full HTML Editor: Visual formatting toolbar
- [x] [Search](https://github.com/mustang-im/mustang/issues/48)
- [x] Setup
  - [x] Mail
  - [x] Chat
  - [x] Calendar
- [x] Settings
- [x] Website
- [x] Meet: Gallery views
- [x] Workspaces
- [ ] Files
  - [x] Grid view
  - [x] Sort order
  - [x] Add files
  - [ ] Set sharing/visibility ?
